In [1]:
import gym
import numpy as np

env = gym.make("Taxi-v3").env
q_table = np.zeros([env.observation_space.n, env.action_space.n])

In [2]:
q_table

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [3]:
import random
from IPython.display import clear_output

# Hyperparameters
alpha = 0.1
gamma = 0.6
epsilon = 0.1

# For plotting metrics
all_epochs = []
all_penalties = []

for i in range(1, 100001):
    state = env.reset()

    epochs, penalties, reward, = 0, 0, 0
    done = False
    
    while not done:
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(q_table[state]) # Exploit learned values

        next_state, reward, done, info = env.step(action) 
        
        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value

        if reward == -10:
            penalties += 1

        state = next_state
        epochs += 1
        
    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")

print("Training finished.\n")

Episode: 100000
Training finished.



In [4]:
q_table

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ -2.41837062,  -2.36395107,  -2.41837065,  -2.36395107,
         -2.27325184, -11.36395107],
       [ -1.87014398,  -1.45024008,  -1.87014398,  -1.45024001,
         -0.7504    , -10.45023701],
       ...,
       [ -1.07392643,   0.41599981,  -0.97647003,  -1.01083724,
         -2.71902709,  -3.44017722],
       [ -2.12935743,  -2.12207123,  -2.1596202 ,  -2.12207204,
         -5.76060489,  -3.71552113],
       [  2.1265016 ,   1.13721912,   2.82774918,  11.        ,
         -2.18585844,  -2.57402809]])

In [5]:
q_table[328]

array([ -2.41157564,  -2.27325184,  -2.3961389 ,  -2.36005462,
       -10.60163933, -10.43517128])

In [6]:
"""Evaluate agent's performance after Q-learning"""

total_epochs, total_penalties = 0, 0
episodes = 100

for _ in range(episodes):
    state = env.reset()
    epochs, penalties, reward = 0, 0, 0
    
    done = False
    
    while not done:
        action = np.argmax(q_table[state])
        state, reward, done, info = env.step(action)

        if reward == -10:
            penalties += 1

        epochs += 1

    total_penalties += penalties
    total_epochs += epochs

print(f"Results after {episodes} episodes:")
print(f"Average timesteps per episode: {total_epochs / episodes}")
print(f"Average penalties per episode: {total_penalties / episodes}")

Results after 100 episodes:
Average timesteps per episode: 13.12
Average penalties per episode: 0.0
